POST http://localhost:8080/alunos HTTP/1.1
content-type: application/json

{
    "nome": "Anderson",
    "senha": "senha123",
    "email": "ander@gmail.com",
    "idade": 25,
    "tipo": "T"
}